[project]
name = "wol-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "getmac>=0.9.5",
    "icmplib>=3.0.4",
    "quart>=0.20.0",
    "quart-cors>=0.8.0",
    "wakeonlan>=3.1.0",
]
